# Compose used for production

version: '3.5'

services:
 leggo-trends:
   image: agoradigital/leggo-trends
   build:
     context: ./
     dockerfile: ./Dockerfile
   volumes:
     - leggo_data:/leggo-trends/leggo_data

volumes:
  leggo_data:
    external:
      name: leggo_data


