# Compose used for production

version: '3.5'

services:
 leggo-trends:
   image: agoradigital/leggo-trends
   build:
     context: ./
     dockerfile: ./Dockerfile
   environment:
      - APP_NAME=${APP_NAME}   
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET_KEY=${TWITTER_API_SECRET_KEY}
   volumes:
     - leggo_data:/leggo-trends/data

volumes:
  leggo_data:
    external:
      name: leggo_data


