# Compose used for production

version: '3.5'

services:
 leggo-trends:
   image: leggo/leggo-trends
   build:
     context: ./
     dockerfile: ./Dockerfile
   volumes:
     - ../leggo-backend/data/:/leggo-trends/data