---
title: "Pressão das proposições pelo Google Trends"
author: "Equipe Leg.go"
date: "12/08/2019"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{r knitr_init, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, paged.print=FALSE, results="asis"}
library(magrittr)
library(tidyverse)
library(readr)
library(plotly)
library(lubridate)

knitr::opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
```

```{r, message=FALSE}
previdencia_nome_formal <- read_csv("../data/nova_previdencia.csv") %>% 
  mutate(nome_formal = "pec 06/2019")

liberdade_economica_nome_formal <- read_csv("../data/liberdade_economica.csv") %>% 
  mutate(nome_formal = "mpv 881/2019 ")

mercado_agua_nome_formal <- read_csv("../data/mercado_da_agua.csv") %>% 
  mutate(nome_formal = "pls 495/2017")

props_nome_formal <- bind_rows(previdencia_nome_formal, 
                               liberdade_economica_nome_formal,
                               mercado_agua_nome_formal)
```


```{r, message=FALSE}
previdencia_apelido <- read_csv("../data/nova_previdencia_apelido.csv") %>% 
  mutate(apelido = "nova previdência")
liberdade_economica_apelido <- read_csv("../data/liberdade_economica_apelido.csv")%>% 
  mutate(apelido = "liberdade econômica")

props_apelido <- bind_rows(previdencia_apelido, 
                               liberdade_economica_apelido)

```

```{r, message=FALSE}
previdencia_comparacao <- read_csv("../data/comparacao_previdencia.csv")
liberdade_economica_comparacao <- read_csv("../data/comparacao_liberdade_economica.csv")
```


```{r}
p <- props_nome_formal %>%  ggplot() + 
  geom_area(aes(x=date, y = pop, fill = nome_formal)) +
  ggplot2::xlab("Tempo") + 
  ggplot2::ylab("Pressão") +
  ggplot2::theme_minimal() +
  ggplot2::facet_grid(rows = vars(nome_formal)) 

ggplotly(p)

```

```{r}
semana <- props_nome_formal %>% 
  mutate(semana = epiweek(date)) %>% 
  group_by(nome_formal, semana) %>% 
  summarise(pop_semana = max(pop))

p <- semana %>%  ggplot() + 
  geom_area(aes(x=semana, y = pop_semana, fill = nome_formal)) +
  ggplot2::xlab("Tempo") + 
  ggplot2::ylab("Pressão") +
  ggplot2::theme_minimal() +
  ggplot2::facet_grid(rows = vars(nome_formal)) 

ggplotly(p)

```

```{r}
p <- props_apelido %>%  ggplot() + 
  geom_area(aes(x=date, y = pop, fill = apelido)) +
  ggplot2::xlab("Tempo") + 
  ggplot2::ylab("Pressão") +
  ggplot2::theme_minimal() +
  ggplot2::facet_grid(rows = vars(apelido)) 

ggplotly(p)

```

```{r}
semana_apelido <- props_apelido %>% 
  mutate(semana = epiweek(date)) %>% 
  group_by(apelido, semana) %>% 
  summarise(pop_semana = max(pop))

p <- semana_apelido %>%  ggplot() + 
  geom_area(aes(x=semana, y = pop_semana, fill = apelido)) +
  ggplot2::xlab("Tempo") + 
  ggplot2::ylab("Pressão") +
  ggplot2::theme_minimal() +
  ggplot2::facet_grid(rows = vars(apelido)) 

ggplotly(p)

```


```{r}
atual_popularidade <- semana_apelido %>% 
  arrange(desc(semana)) %>% 
  head(4) %>% 
  arrange(apelido, semana) %>% 
  mutate(pop_ant = lag(pop_semana)) %>% 
  arrange(desc(semana)) %>% 
  head(2)

# p <- atual_popularidade %>%
#   ggplot() +
#   geom_histogram(aes(x=apelido, y=value), stat = "identity", fill = "red", width = 0.6) +
#   geom_histogram(aes(x=apelido, y=value), stat = "identity", fill = "blue", width = 0.2, position = "dodge")

p <- ggplot(data=atual_popularidade,aes(x=apelido, y=pop_semana))+
  geom_bar(aes(y=100),stat="identity",position ="identity",alpha=0.4,fill='grey', width = 0.4) +
  geom_bar(aes(y=pop_ant), stat="identity", position ="identity", alpha=.6, fill='pink', width = 0.3) +
  geom_bar(aes(y=pop_semana), stat="identity", position ="identity", alpha=.4, fill='red', width = 0.2) +
  coord_cartesian(ylim = c(0, 100)) +
  theme_minimal()


ggplotly(p)
```